import Header from '../components/header/Header';
import './global.css';

export const metadata = {
  title: 'Welcome to web-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="mx-1 md:mx-8">{children}</main>
      </body>
    </html>
  );
}
