import { Provider } from 'react-redux';
import Header from '../components/header/Header';
import './global.css';
import store from '../store/user/store';
import { AuthProvider } from '../store/context/auth';

export const metadata = {
  title: 'Welcome to web-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Header />
          <main className="mx-1 md:mx-8">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
