import Header from '../components/header/Header';
import './global.css';
import { AuthProvider } from '../store/context/auth';
import { CartProvider } from '../store/context/cart';
import Footer from '../components/footer/Foooter';

export const metadata = {
  title: 'Welcome to web-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <CartProvider>
            <Header />
            <main className="mx-1 md:mx-8">{children}</main>
            <Footer />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
